In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)

In [ ]:
df=pd.read_csv(r"/content/train.csv", encoding='latin1')

In [ ]:
df.sample(5)

,textID,text,selected_text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
3355,dbb159d94c,omg a rat... ewwwww. omg i cant wait for tha marra.. so ecxcited. annabel cant go tho,omg a rat... ewwwww. omg i cant wait for tha marra.. so ecxcited. annabel cant go tho,neutral,noon,21-30,Tunisia,11818619,155360.0,76
9224,2cd25bd667,Allergies suck ducks nuts. <=====8=====>,Allergies suck,negative,night,31-45,Senegal,16743927,192530.0,87
9923,892119c199,MY PUFFFFY IS LEAVINGGGGGGG NOOOOOOOOO,MY PUFFFFY IS LEAVINGGGGGGG NOOOOOOOOO,negative,night,70-100,Guyana,786552,196850.0,4
17682,f1dadac45b,"Welcome to Twitter It`s really cool that you are here! Greetings from Vienna,Austria",ly coo,positive,morning,0-20,Eritrea,3546421,101000.0,35
13978,c41582b2e2,"Hmm, $25 to see the Decemberists, but I have to go to Raleigh on a work night... or $95 for cheap seats to the Bolshoi? Probably neither",cheap se,negative,noon,60-70,Cyprus,1207359,9240.0,131

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27481 entries, 0 to 27480
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   textID            27481 non-null  object
 1   text              27480 non-null  object
 2   selected_text     27480 non-null  object
 3   sentiment         27481 non-null  object
 4   Time of Tweet     27481 non-null  object
 5   Age of User       27481 non-null  object
 6   Country           27481 non-null  object
 7   Population -2020  27481 non-null  int64
 8   Land Area (Km²)   27481 non-null  float64
 9   Density (P/Km²)   27481 non-null  int64
dtypes: float64(1), int64(2), object(7)
memory usage: 2.1+ MB

In [ ]:
df.drop(columns=['selected_text','textID','Land Area (Km²)', 'Density (P/Km²)','Population -2020' ], inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27481 entries, 0 to 27480
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   text           27480 non-null  object
 1   sentiment      27481 non-null  object
 2   Time of Tweet  27481 non-null  object
 3   Age of User    27481 non-null  object
 4   Country        27481 non-null  object
dtypes: object(5)
memory usage: 1.0+ MB

In [ ]:
df['text'] = df['text'].astype(str)

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop = set(stopwords.words('english'))

df['text'] = df['text'].apply(lambda x: ' '.join([word for word in str(x).split() if word not in stop]))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [ ]:
def clean_and_remove_stopwords(text):
    if not isinstance(text, str):
        return ""
    return ' '.join([word for word in text.split() if word not in stop])

df['text'] = df['text'].apply(clean_and_remove_stopwords)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27481 entries, 0 to 27480
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   text           27481 non-null  object
 1   sentiment      27481 non-null  object
 2   Time of Tweet  27481 non-null  object
 3   Age of User    27481 non-null  object
 4   Country        27481 non-null  object
dtypes: object(5)
memory usage: 1.0+ MB

In [ ]:
df.head(5)

,text,sentiment,Time of Tweet,Age of User,Country
0,"i`d responded, i going",neutral,morning,0-20,Afghanistan
1,sooo sad i miss san diego!!!,negative,noon,21-30,Albania
2,boss bullying me...,negative,night,31-45,Algeria
3,interview! leave alone,negative,morning,46-60,Andorra
4,"sons ****, couldn`t put releases already bought",negative,noon,60-70,Angola

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27481 entries, 0 to 27480
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   text           27481 non-null  object
 1   sentiment      27481 non-null  object
 2   Time of Tweet  27481 non-null  object
 3   Age of User    27481 non-null  object
 4   Country        27481 non-null  object
dtypes: object(5)
memory usage: 1.0+ MB

In [ ]:
df['sentiment'].value_counts()

sentiment
neutral     11118
positive     8582
negative     7781
Name: count, dtype: int64

In [ ]:
df['Time of Tweet'].value_counts()

In [ ]:
df['Age of User'].value_counts()

In [ ]:
df.isnull().sum()

In [ ]:
time_map = {
    'morning': 0,
    'noon': 1,
    'night': 2
}

df['Time of Tweet'] = df['Time of Tweet'].map(time_map)

In [ ]:
sentiment_map = {
    'negative': 0,
    'neutral': 1,
    'positive': 2
}

df['sentiment'] = df['sentiment'].map(sentiment_map)

In [ ]:
df['text'] = df['text'].astype(str) 

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
stop = set(stopwords.words('english'))

df['text'] = df['text'].apply(lambda x: ' '.join([word for word in str(x).split() if word not in stop]))

In [ ]:
def clean_and_remove_stopwords(text):
    if not isinstance(text, str):
        return ""
    return ' '.join([word for word in text.split() if word not in stop])

df['text'] = df['text'].apply(clean_and_remove_stopwords)

In [ ]:
def safe_text_clean(text):
    if not isinstance(text, str):
        return ''
    return text.lower()

df['text'] = df['text'].apply(safe_text_clean)

In [ ]:
df.info()

In [ ]:
df['Age of User'].value_counts()

In [ ]:
Age_of_User_map = {
    '0-20': 0,
    '21-30': 1,
    '31-45': 2,
    '46-60':3,
    '60-70':4,
    '70-100':5
}

df['Age of User'] = df['Age of User'].map(Age_of_User_map)

In [ ]:
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification
import os

model_name = "cardiffnlp/twitter-roberta-base-sentiment"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

classifier = pipeline('sentiment-analysis', model=model, tokenizer=tokenizer)

text = "I love the power of RoBERTa model for sentiment analysis!"

result = classifier(text)

print(f"Input: {text}")
print(f"Sentiment prediction: {result}")

In [ ]:
df.sample(5)

In [ ]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

model_name = "cardiffnlp/twitter-roberta-base-sentiment"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

classifier = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer)

user_text = input("Enter a statement: ")

result = classifier(user_text)[0]

label_map = {
    "LABEL_0": "Negative",
    "LABEL_1": "Neutral",
    "LABEL_2": "Positive"
}

sentiment = label_map[result['label']]
confidence = result['score']

print(f"Sentiment: {sentiment}")
print(f"Confidence: {confidence:.4f}")